# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_packages:
 - covr

r_github_packages:
  - jimhester/lintr

before_install:
  - cd $REPO_TO_TEST

env:
  matrix:
        - REPO_TO_TEST=tmcRtestrunner
        - REPO_TO_TEST=tmcrstudioaddin

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'lintr::lint_package()'
